config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :pickups
  resources :places
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pickup.rb
class Pickup < ApplicationRecord
    belongs_to :passenger, class_name: 'User', foreign_key: :passenger_id
    belongs_to :place

    validate :departure_time_cannot_be_in_the_past

    def departure_time_cannot_be_in_the_past
        if departure_time.present? && departure_time < Date.today
            errors.add(:departure_time, "can't be in the past")
        end
    end 
end

app/models/place.rb
class Place < ApplicationRecord
    has_many :trips
    has_many :pickups
    
    validates :name, :longitude, :latitude, presence: true
    validates_uniqueness_of :name
    validates :longitude, uniqueness: { scope: :latitude }
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :driver, class_name: 'User', foreign_key: :driver_id
    belongs_to :place
    
    validate :no_departure_time_in_the_past
    validates_presence_of :driver, :source_id, :destination_id
    validates :no_of_seats, numericality: { greater_than_or_equal_to: 3 }

    def no_departure_time_in_the_past
        if departure_time.present? && departure_time < Date.today
        errors.add(:departure_time, "can't be in the past")
        end
    end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, class_name: 'User', foreign_key: :driver_id
  has_many :pickups, class_name: 'User', foreign_key: :passenger_id

  extend Enumerize

  enumerize :role, in: {:driver => 1, :passenger => 2}

  validates :full_name, :phone, presence: true
  validates_length_of :full_name, :minimum => 6, :allow_blank => true
  validates :phone, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :phone, :role])
    end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :set_pickup, only: [:show, :edit, :update, :destroy]

  # GET /pickups
  # GET /pickups.json
  def index
    @pickups = Pickup.all
  end

  # GET /pickups/1
  # GET /pickups/1.json
  def show
  end

  # GET /pickups/new
  def new
    @pickup = Pickup.new
  end

  # GET /pickups/1/edit
  def edit
  end

  # POST /pickups
  # POST /pickups.json
  def create
    @pickup = Pickup.new(pickup_params)

    respond_to do |format|
      if @pickup.save
        format.html { redirect_to @pickup, notice: 'Pickup was successfully created.' }
        format.json { render :show, status: :created, location: @pickup }
      else
        format.html { render :new }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pickups/1
  # PATCH/PUT /pickups/1.json
  def update
    respond_to do |format|
      if @pickup.update(pickup_params)
        format.html { redirect_to @pickup, notice: 'Pickup was successfully updated.' }
        format.json { render :show, status: :ok, location: @pickup }
      else
        format.html { render :edit }
        format.json { render json: @pickup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pickups/1
  # DELETE /pickups/1.json
  def destroy
    @pickup.destroy
    respond_to do |format|
      format.html { redirect_to pickups_url, notice: 'Pickup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pickup
      @pickup = Pickup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pickup_params
      params.require(:pickup).permit(:departure_time, :passenger_id, :source_id, :destination_id)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :longitude, :latitude)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:departure_time, :no_of_seats, :driver_id, :source_id, :destination_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pickups_helper.rb
module PickupsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
    def get_places
        x = Place.order(:name).select([ :name, :id ])
        return x.map{ |y| [ y.name, y.id ] }
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raye7Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pickups/_form.html.erb
<% selected_places = get_places %>
<%= form_with(model: pickup, local: true) do |f| %>
  <% if pickup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pickup.errors.count, "error") %> prohibited this pickup from being saved:</h2>

      <ul>
        <% pickup.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Passenger %><br />
    <%= f.text_field :passenger_id, autofocus: true, autocomplete: "passenger_id" %>
  </div>

  <div class="field">
    <%= f.label :Source %><br />
    <%= f.select(:source_id, options_for_select(selected_places, @trip&.source_id), {include_blank: true}, {class: "select2 col-sm-4"}) %>
  </div>

  <div class="field">
    <%= f.label :Destination %><br />
    <%= f.select(:destination_id, options_for_select(selected_places, @trip&.destination_id), {include_blank: true}, {class: "select2 col-sm-4"}) %>
  </div>

  <div class="field">
    <%= f.label :Departure_time %><br />
    <%= f.number_field :departure_time, autofocus: true, autocomplete: "departure_time" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pickups/edit.html.erb
<h1>Editing Pickup</h1>

<%= render 'form', pickup: @pickup %>

<%= link_to 'Show', @pickup %> |
<%= link_to 'Back', pickups_path %>

app/views/pickups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pickups</h1>

<table>
  <thead>
    <tr>
      <th>Passenger</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Departure Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pickups.each do |pickup| %>
      <tr>
        <td><%= pickup.passenger_id %></td>
        <td><%= pickup.source_id %></td>
        <td><%= pickup.destination_id %></td>
        <td><%= pickup.departure_time %></td>
        <td><%= link_to 'Show', pickup %></td>
        <td><%= link_to 'Edit', edit_pickup_path(pickup) %></td>
        <td><%= link_to 'Destroy', pickup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pickup', new_pickup_path %>

app/views/pickups/new.html.erb
<h1>New Pickup</h1>

<%= render 'form', pickup: @pickup %>

<%= link_to 'Back', pickups_path %>

app/views/pickups/show.html.erb
<p>
  <strong>Passenger:</strong>
  <%= @pickup.passenger_id %>
</p>
 
<p>
  <strong>Source:</strong>
  <%= @pickup.source_id %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @pickup.destination_id %>
</p>

<p>
  <strong>Departure Time:</strong>
  <%= @pickup.departure_time %>
</p>

<%= link_to 'Edit', edit_pickup_path(@pickup) %> |
<%= link_to 'Back', pickups_path %>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |f| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :longitude %><br />
    <a class="btn" href="#" id="location-picker"></a>
    <%= f.number_field :longitude, id: 'longitude', class: "inline-control", within: -91...91, step: 'any', required: true %>
  </div>

  <div class="field">
    <%= f.label :latitude %><br />
    <a class="btn" href="#" id="location-picker"></a>
    <%= f.number_field :latitude, id: 'latitude', class: "inline-control", within: -91...91, step: 'any', required: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>longitude</th>
      <th>latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.longitude %></td>
        <td><%= place.latitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>
 
<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/trips/_form.html.erb
<% selected_places = get_places %>
<%= form_with(model: trip, local: true) do |f| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Driver %><br/>
    <%= f.text_field :driver_id, autofocus: true, autocomplete: "driver_id" %>
  </div>

  <div class="field">
    <%= f.label :Source %><br />
    <%= f.select(:source_id, options_for_select(selected_places, @trip&.source_id), {include_blank: true}, {class: "select2 col-sm-4"}) %>
  </div>

  <div class="field">
    <%= f.label :Destination %><br />
    <%= f.select(:destination_id, options_for_select(selected_places, @trip&.destination_id), {include_blank: true}, {class: "select2 col-sm-4"}) %>
  </div>

  <div class="field">
    <%= f.label :Departure_time %><br />
    <%= f.number_field :departure_time, autofocus: true, autocomplete: "departure_time" %>
  </div>

  <div class="field">
    <%= f.label :No_of_seats %><br />
    <%= f.number_field :no_of_seats, autofocus: true, autocomplete: "no_of_seats" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Driver</th>
      <th>Source</th>
      <th>Destination</th>
      <th>Departure Time</th>
      <th>No of Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.driver_id %></td>
        <td><%= trip.source_id %></td>
        <td><%= trip.destination_id %></td>
        <td><%= trip.departure_time %></td>
        <td><%= trip.no_of_seats %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>